// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://varlljbeopdbbpzuavaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcmxsamJlb3BkYmJwenVhdmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDU5NTMsImV4cCI6MjA4NTYyMTk1M30.mDUendgpIHTKPf4T5KWLVQ8q6KjZoWr2e8qGY33kIAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});